version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  terraform-provider-powerbi:

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace/terraform-provider-powerbi
      - ~/.ssh:/home/vscode/.ssh-localhost:ro

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    networks:
      - network

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

networks:
  network:
    driver: bridge
    name: dev_network
